#
# MakeMKV settings file, written by MakeMKV v1.18.1 darwin(arm64-release)
#

kslc_952d0b6318f8d1f3 = "000004fc"
kslc_f7a25b555f6eeee0 = "0000040d"
path_DestDirMRU = "*/Users/Shared/Flesh for Frankenstein*/Users/Shared*/Users/cwalker"
path_OpenFile = "/Users/Shared/"
screen_geometry = "AdnQywADAAAAAARdAAADFQAACHUAAAY4AAAEXQAAAzEAAAh1AAAGOAAAAAAAAAAADwAAAARdAAADMQAACHUAAAY4"
screen_state = "AAAA/wAAAAD9AAAAAAAABBkAAAKxAAAABAAAAAQAAAAIAAAACPwAAAABAAAAAgAAAAEAAAAWAE0AYQBpAG4AVABvAG8AbABiAGEAcgEAAAAA/////wAAAAAAAAAA"

