#
# MakeMKV settings file, written by MakeMKV v1.18.1 darwin(arm64-release)
#

app_DestinationDir = "/Users/Shared"
app_DestinationType = "2"
app_Java = ""
app_Key = "T-iyhMMBV8nWtNo3BgMdcvypH8UL01nYmww2zFzQDtiZsdJUOaAuCURsPRQ1Hj3i75RE"
app_Proxy = ""
app_ccextractor = ""
sdf_Stop = ""

