github.com:
    users:
        chad3814:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: chad3814
